superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))

]

superhero_project/superheroes/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('edit<int:hero_id>/', views.edit, name='edit'),
    path('delete<int:hero_id>/', views.delete, name='delete'),
]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superhero_project/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero


# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)
    
def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        #save the form contents as a new db object
        #return to index
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else: 
        return render(request, 'superheroes/create.html')

def edit(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    if request.method == "POST":
        id = single_hero.id
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_ability = request.POST.get('primary_ability')
        secondary_ability = request.POST.get('secondary_ability')
        catch_phrase = request.POST.get('catchphrase')
        
        update_hero = Superhero(id, name, alter_ego, primary_ability, secondary_ability, catch_phrase)
        update_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/edit.html', context)

def delete(request, hero_id):
    delete_item = Superhero.objects.get(pk=hero_id)
    delete_item.delete()
    return HttpResponseRedirect(reverse('superheroes:index'))

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action="{% url 'superheroes:create' %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="Add!">
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Hero</title>
</head>
<body>
    
</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hero Details</title>
</head>
<body>
  <ul>
      <li><h3>Name: {{single_hero.name}}</h3></li>
      <li><h3>Alter Ego: {{single_hero.alter_ego}}</h3></li>
      <li><h3>Primary Ability: {{single_hero.primary_ability}}</h3></li>
      <li><h3>Secondary Ability: {{single_hero.secondary_ability}}</h3></li>
      <li><h3>Catchphrase: "{{single_hero.catch_phrase}}"</h3></li>


  </ul>
  
</body>
</html>

superhero_project/superheroes/templates/superheroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Hero</title>
</head>
<body>
       
   <h1>Please make your desired edits to  {{single_hero.name}}. </h1> 
            
    <form method="post">
    {% csrf_token %}
        <p>Super Hero <input type = "text" name="name" id ="name" value="{{single_hero.name}}"></p>
            
        <p>Alter Ego: <input type = "text"  name="alter_ego" id="alter_ego" value="{{single_hero.alter_ego}}"></p>
               
        <p>Primary Ability: <input type="text"  name ="primary_ability" id = "primary_ability" value="{{single_hero.primary_ability}}"></p>
                
        <p>Secondary Ability: <input type="text"  name="secondary_ability" id="secondary_ability" value="{{single_hero.secondary_ability}}"></p>
               
        <p>Catchphrase: <input type="text"  name="catchphrase" id="catchphrase" value="{{single_hero.catch_phrase}}"></p>
              
        <input type="submit" value="Save">
            
    </form>
          
</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    {% load static %}
    <img src="{% static 'superheroes/Superhero-Group.jpg' %}" alt="Superhero Group Photo">
    <h1>List of Heroes</h1>
    <ul>
        {% for hero in all_heroes %}
        <li> <h2>{{hero.name}} - <a href="{% url 'superheroes:detail' hero.id %}">Click for Superhero Details</a></h2> </li>
        <li> <h2><a href="{% url 'superheroes:edit' hero.id %}">Edit Hero</a></h2></li>
        <li><h2><a href="{% url 'superheroes:delete' hero.id %}">Delete Hero</a></h2></li>
        
        
        {% endfor %}
       

    </ul>

    <h2><a href ="{% url 'superheroes:create'%}">Add New Hero</a></h2>
</body>
</html>